version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-imbox-ciso-web
    image: message-imbox-ciso:latest
    ports:
      - "3027:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    restart: always 

  db:
    image: sqlite:latest
    container_name: message-imbox-ciso-db
    volumes:
      - db_data:/var/lib/sqlite
    restart: always 

volumes:
  db_data:
