version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-imbox-ciso-web
    image: message-imbox-ciso:latest
    ports:
      - "3027:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: >
      sh -c "flask db init && flask db migrate -m 'Initial migration' && flask db upgrade && flask run --host=0.0.0.0"
    restart: always

volumes:
  db_data:
